### ISSUE TITLE
Crashing due to spam

### ISSUE THREAD

**Issue by OrbitalT** [Dwyte/CipherChat#1]
The app lags due to large amounts of spam and user activity. other than that great app and i will definitely be glad to help work on this.

**Comment by Dwyte** [comment]
wooooo ye, got my first issue on github hehe. it was indeed crazy awhile ago I wasn't really expecting that much people would come around test the app. wasn't ready fighting spam.

**Comment by Dwyte** [comment]
anyway I think the issue is the one react is warning me about is that theres memory leaks, when I switch between private channel to global channel I see a warning OK nto the console that I cant update react c OK mponent while its unmounted blabla and it introduces memory leaks thus I need to unsubscribe from all occuring promises,  when I was testing it alone it didnt really affect while I was testing it so I just didnt bother but I did try searching about ut

**Comment by Dwyte** [comment]
I pushed some new updates fixing the memory leaks
